# This file was generated by GoReleaser. DO NOT EDIT.
cask "mediainfo" do
  binary "mediainfo", target: "go-mediainfo"
  caveats <<~EOS
    If you already have Homebrew's MediaInfo installed, the `mediainfo` symlink may already exist.
    Use `go-mediainfo` to run this cask's binary.
  EOS

  name "mediainfo"
  desc "Go rewrite of MediaInfo CLI."
  homepage "https://github.com/autobrr/go-mediainfo"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mediainfo"

  on_macos do
    on_intel do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_amd64.tar.gz"
      sha256 "d8aa1d31ed467b849829ca8867971c16c21181ad3c69766d18a49cda07e80cd7"
    end
    on_arm do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_arm64.tar.gz"
      sha256 "a4672c8cc3b86c1290f220a589282f9597b43db177566959c907652008ca57c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_amd64.tar.gz"
      sha256 "28b8f0743f59c757c87339f8fadcd6110560a84bd692d7f485f4dc7b289ca5b4"
    end
    on_arm do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_arm64.tar.gz"
      sha256 "adac19ebce7fb4818508ee227580c98083bbc6aef233b21ab931092962658579"
    end
  end

  # No zap stanza required
end
